DROP TABLE IF EXISTS participation_requests CASCADE;

CREATE TABLE IF NOT EXISTS participation_requests(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id          BIGINT NOT NULL,
    requester_id      BIGINT NOT NULL,
    status            VARCHAR(20)                             NOT NULL,
    CONSTRAINT uq_req_ev UNIQUE (requester_id, event_id)
);