server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**,
            - /categories/**,
            - /compilations/**,
            - /admin/events/**,
            - /admin/categories/**,
            - /admin/compilations/**,
            - /users/*/events/**
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**,
            - /events/*/comments**,
            - /comments/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**,
            - /users/{userId}/events/{eventId}/requests/**,
              /admin/requests/**
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**,
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG