server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/events/**,/users/*/events/**,/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/users/*/events/**,/users/*/comments/**,/events/*/comments/**,/comments/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/internal/requests/**,/users/*/requests/**,/users/*/events/*/requests/**
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG