DROP TABLE IF EXISTS event_compilations CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS event_locations CASCADE;
DROP TABLE IF EXISTS event_categories CASCADE;

CREATE TABLE event_categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE event_locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL
);

CREATE TABLE events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(120),
    annotation        VARCHAR(2000) NOT NULL,
    description       VARCHAR(7000) NOT NULL,
    category_id       BIGINT NOT NULL,
    created_on        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id      BIGINT NOT NULL,
    is_paid           BOOLEAN,
    participant_limit INTEGER,
    published_on      TIMESTAMP WITHOUT TIME ZONE,
    is_moderated      BOOLEAN,
    state             VARCHAR(16) NOT NULL,
    location_id       BIGINT,

    CONSTRAINT fk_event_category FOREIGN KEY (category_id)
                            REFERENCES event_categories (id),
    CONSTRAINT fk_event_location FOREIGN KEY (location_id)
                            REFERENCES event_locations (id)
);

CREATE TABLE compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(100),
    pinned BOOLEAN
);

CREATE TABLE event_compilations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT NOT NULL,
    author_id  BIGINT NOT NULL,
    text       VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);