DROP TABLE IF EXISTS event_compilations CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS event_locations CASCADE;
DROP TABLE IF EXISTS event_categories CASCADE;


CREATE TABLE IF NOT EXISTS event_categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) UNIQUE,
    CONSTRAINT pk_event_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat DOUBLE PRECISION                        NOT NULL,
    lon DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_event_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(120),
    annotation           VARCHAR(2000)                            NOT NULL,
    description          VARCHAR(7000)                           NOT NULL,
    category_id          BIGINT REFERENCES event_categories (id) ON DELETE CASCADE,
    created_on           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_date_time      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    owner_id             BIGINT NOT NULL,
    is_paid              BOOLEAN,
    participant_limit    INTEGER,
    confirm_request      INTEGER,
    published_on         TIMESTAMP WITHOUT TIME ZONE,
    is_moderated         BOOLEAN,
    state                VARCHAR(16)                             NOT NULL,
    location_id          BIGINT REFERENCES event_locations (id),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(100),
    pinned BOOLEAN,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilations(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES events (id) ON DELETE CASCADE
);