DROP TABLE IF EXISTS event_categories CASCADE;
DROP TABLE IF EXISTS event_locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS event_compilations CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE event_categories (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE event_locations (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 lat DOUBLE PRECISION NOT NULL,
                                 lon DOUBLE PRECISION NOT NULL,
                                 CONSTRAINT uq_location_coords UNIQUE (lat, lon)
);

CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(120) NOT NULL,
                        annotation VARCHAR(2000) NOT NULL,
                        description VARCHAR(7000) NOT NULL,
                        category_id BIGINT NOT NULL,
                        created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        event_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        initiator_id BIGINT NOT NULL,
                        confirmed_requests INTEGER DEFAULT 0,
                        paid BOOLEAN DEFAULT FALSE,
                        participant_limit INTEGER,
                        published_on TIMESTAMP WITHOUT TIME ZONE,
                        is_moderated BOOLEAN DEFAULT FALSE,
                        state VARCHAR(16) NOT NULL,
                        location_id BIGINT,
                        CONSTRAINT fk_event_category FOREIGN KEY (category_id)
                            REFERENCES event_categories (id) ON DELETE RESTRICT,
                        CONSTRAINT fk_event_location FOREIGN KEY (location_id)
                            REFERENCES event_locations (id) ON DELETE SET NULL
);
CREATE INDEX idx_events_category_id ON events (category_id);
CREATE INDEX idx_events_initiator_id ON events (initiator_id);
CREATE INDEX idx_events_state ON events (state);
CREATE INDEX idx_events_event_date ON events (event_date_time);

CREATE TABLE compilations (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              title VARCHAR(100) NOT NULL,
                              pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE event_compilations (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    compilation_id BIGINT NOT NULL,
                                    event_id BIGINT NOT NULL,
                                    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
                                    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
                                    CONSTRAINT uq_compilation_event UNIQUE (compilation_id, event_id)
);

CREATE INDEX idx_event_compilations_event_id ON event_compilations (event_id);
CREATE INDEX idx_event_compilations_compilation_id ON event_compilations (compilation_id);
CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          event_id BIGINT NOT NULL,
                          author_id BIGINT NOT NULL,
                          text VARCHAR(1000) NOT NULL,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                          CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES events(id)
);
CREATE INDEX idx_comments_event_id ON comments (event_id);
CREATE INDEX idx_comments_author_id ON comments (author_id);
CREATE INDEX idx_comments_created_at ON comments (created_at);