spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
        - id: stats_server_route
          uri: lb://stats-server
          predicates:
            - Path=/**
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG